"""created order and order item tables

Revision ID: f9b5dc28ac1e
Revises: 7754bf8489a0
Create Date: 2023-10-17 10:17:38.095667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b5dc28ac1e'
down_revision: Union[str, None] = '7754bf8489a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
